// TODO: replace any with EventProps from types/event.ts

import { EventListingProps } from '@/types/event';

// TODO: remove this after API integration with events endpoint is done
export const mockEventsForCards: EventListingProps[] = [
  {
    id: 1,
    userId: 1,
    name: 'NY Sevens',
    type: 'open',
    country: 'US',
    division: 'mens',
    dateStart: '06/12/2021',
    entryFees: 'Free - $15',
    league: 'Homebush',
    teams: 18,
    status: 'live',
    series: { id: 1, name: 'Series 1' },
    location: 'Edwin Flack Avenue, Sydney, Olympic Park, 2127',
    divisions: 'Men’s, Mixed, Women’s, Youth…',
  },
  {
    id: 2,
    userId: 2,
    name: 'League of Legends',
    logo: '/images/mock/logo3-thumb.png',
    type: 'draft',
    country: 'CA',
    division: 'womens',
    dateStart: '09/14/2021',
    entryFees: 'Free - $25',
    teams: 18,
    status: 'closed',
    series: { id: 2, name: 'Series 2' },
  },
  {
    id: 3,
    userId: 3,
    name: 'Ladies Spring Open',
    photo: '/images/mock/event2-thumb.jpg',
    logo: '/images/mock/logo2-thumb.png',
    type: 'draft',
    country: 'AU',
    division: 'womens',
    teams: 5,
    status: 'open',
    series: { id: 3, name: 'Series 3' },
  },
  {
    id: 4,
    userId: 4,
    name: 'NY Sevens',
    photo: '/images/mock/event4-thumb.jpg',
    logo: '/images/mock/logo4-thumb.png',
    type: 'open',
    country: 'US',
    division: 'mens',
    teams: 18,
    status: 'live',
    series: { id: 4, name: 'Series 4' },
  },
  {
    id: 5,
    userId: 5,
    name: 'NY Sevens',
    photo: '/images/mock/event2-thumb.jpg',
    logo: '/images/mock/logo2-thumb.png',
    type: 'open',
    country: 'US',
    division: 'womens',
    teams: 18,
    status: 'open',
    series: { id: 5, name: 'Series 5' },
  },
  {
    id: 6,
    userId: 6,
    name: 'Ice Fourths',
    photo: 'https://source.unsplash.com/XP2goMOgHX8/400x300',
    logo: '/images/mock/logo5-thumb.png',
    type: 'draft',
    country: 'IS',
    division: 'mens',
    teams: 18,
    status: 'closed',
    series: { id: 6, name: 'Series 6' },
  },
  {
    id: 7,
    userId: 7,
    name: 'NY Sevens',
    photo: 'https://source.unsplash.com/KWQ2kQtxiKE/400x300',
    type: 'open',
    country: 'IN',
    division: 'mens',
    teams: 18,
    status: 'closed',
    series: { id: 7, name: 'Series 7' },
  },
  {
    id: 8,
    userId: 8,
    name: 'NY Sevens',
    photo: 'https://source.unsplash.com/Ys85uMksDHc/400x300',
    type: 'draft',
    country: 'US',
    division: 'womens',
    teams: 18,
    status: 'open',
    series: { id: 8, name: 'Series 8' },
  },
  {
    id: 9,
    userId: 9,
    name: 'Lorem League',
    photo: 'https://source.unsplash.com/jcshdOBf2kE/400x300',
    logo: '/images/mock/logo6-thumb.png',
    type: 'open',
    country: 'UK',
    division: 'mens',
    teams: 18,
    status: 'open',
    series: { id: 9, name: 'Series 9' },
  },
  {
    id: 10,
    userId: 1,
    name: 'Ipsum Four',
    photo: 'https://source.unsplash.com/sBg4-N4vf4A/400x300',
    type: 'open',
    country: 'IS',
    division: 'mens',
    teams: 18,
    status: 'live',
    series: { id: 1, name: 'Series 1' },
  },
  {
    id: 11,
    userId: 2,
    name: 'Legends Legue',
    photo: 'https://source.unsplash.com/ymVaGKsBQXM/400x300',
    logo: '/images/mock/logo3-thumb.png',
    type: 'draft',
    country: 'CA',
    division: 'womens',
    teams: 18,
    status: 'closed',
    series: { id: 2, name: 'Series 2' },
  },
  {
    id: 12,
    userId: 2,
    name: 'Girls Spring Open',
    photo: 'https://source.unsplash.com/zs4Pahjo5ww/400x300',
    logo: '/images/mock/logo5-thumb.png',
    type: 'draft',
    country: 'AU',
    division: 'womens',
    teams: 5,
    status: 'open',
    series: { id: 2, name: 'Series 3' },
  },
  {
    id: 13,
    userId: 2,
    name: 'BA Champoinship',
    photo: 'https://source.unsplash.com/Zs_o1IjVPt4/400x300',
    logo: '/images/mock/logo4-thumb.png',
    type: 'open',
    country: 'CA',
    division: 'mens',
    teams: 18,
    status: 'live',
    series: { id: 2, name: 'Series 4' },
  },
];

export const eventColumns: string[] = [
  'Type',
  'Name',
  'League',
  'Country',
  'Series',
  'Date Start',
  'Entry Fees',
  'Status',
  'Location',
  'Divisions',
  'Teams',
  'Edit',
];
