// TODO: replace any with EventProps from types/event.ts

import { EventListingProps } from '@/types/event';

// TODO: remove this after API integration with events endpoint is done
export const mockEventsForCards: EventListingProps[] = [
  {
    id: 1,
    userId: 1,
    name: 'NY Sevens',
    type: 'open',
    division: 'mens',
    dateStart: '06/12/2021',
    entryFees: 'Free - $15',
    league: 'Homebush',
    country: 'us',
    teams: 18,
    status: 'live',
    series: { id: 1, name: 'Series 1' },
    location: 'Edwin Flack Avenue, Sydney, Olympic Park, 2127',
    divisions: 'Men’s, Mixed, Women’s, Youth…',
  },
  {
    id: 2,
    userId: 2,
    name: 'NY Sevens',
    type: 'draft',
    division: 'womens',
    dateStart: '09/14/2021',
    entryFees: 'Free - $25',
    country: 'gb',
    teams: 18,
    status: 'closed',
    series: { id: 2, name: 'Series 2' },
  },
  {
    id: 3,
    userId: 3,
    name: 'Ladies Spring Open',
    photo: '/images/mock/event2-thumb.jpg',
    logo: '/images/mock/logo2-thumb.png',
    type: 'draft',
    country: 'au',
    division: 'womens',
    teams: 5,
    status: 'open',
    series: { id: 3, name: 'Series 3' },
  },
  {
    id: 4,
    userId: 4,
    name: 'NY Sevens',
    type: 'open',
    division: 'mens',
    teams: 18,
    status: 'live',
    series: { id: 4, name: 'Series 4' },
  },
  {
    id: 5,
    userId: 5,
    name: 'NY Sevens',
    type: 'open',
    division: 'womens',
    teams: 18,
    status: 'open',
    series: { id: 5, name: 'Series 5' },
  },
  {
    id: 6,
    userId: 6,
    name: 'NY Sevens',
    type: 'draft',
    division: 'mens',
    teams: 18,
    status: 'closed',
    series: { id: 6, name: 'Series 6' },
  },
  {
    id: 7,
    userId: 7,
    name: 'NY Sevens',
    type: 'open',
    division: 'mens',
    teams: 18,
    status: 'closed',
    series: { id: 7, name: 'Series 7' },
  },
  {
    id: 8,
    userId: 8,
    name: 'NY Sevens',
    type: 'draft',
    division: 'womens',
    teams: 18,
    status: 'open',
    series: { id: 8, name: 'Series 8' },
  },
  {
    id: 9,
    userId: 9,
    name: 'NY Sevens',
    type: 'open',
    division: 'mens',
    teams: 18,
    status: 'open',
    series: { id: 9, name: 'Series 9' },
  },
];

export const eventColumns: string[] = [
  'Type',
  'Name',
  'League',
  'Country',
  'Series',
  'Date Start',
  'Entry Fees',
  'Status',
  'Location',
  'Divisions',
  'Teams',
  'Edit',
];
