import { LeagueProps } from "@/types/league";

export const mockLeagues: LeagueProps[] = [
  {
    id: 1,
    leagueName: "HomeBush 1",
    status: "active",
    country: 'us',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'No',
    isSanctioned: false,
    championshipQualifier: true,
  },
  {
    id: 2,
    leagueName: "HomeBush 2",
    status: "inactive",
    country: 'au',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'yes',
    isSanctioned: true,
    championshipQualifier: false,
  },
  {
    id: 3,
    leagueName: "HomeBush 3",
    status: "active",
    country: 'in',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'yes',
    isSanctioned: false,
    championshipQualifier: true,
  },
  {
    id: 4,
    leagueName: "HomeBush 4",
    status: "pending",
    country: 'ph',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'No',
    isSanctioned: false,
    championshipQualifier: true,
  },
  {
    id: 5,
    leagueName: "HomeBush 5",
    status: "active",
    country: 'us',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'yes',
    isSanctioned: false,
    championshipQualifier: false,
  },
  {
    id: 6,
    leagueName: "HomeBush 6",
    status: "active",
    country: 'us',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'No',
    isSanctioned: false,
    championshipQualifier: false,
  },
  {
    id: 7,
    leagueName: "HomeBush 7",
    status: "blocked",
    country: 'us',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'yes',
    isSanctioned: false,
    championshipQualifier: true,
  },
  {
    id: 8,
    leagueName: "HomeBush 8",
    status: "active",
    country: 'us',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'yes',
    isSanctioned: false,
    championshipQualifier: true,
  },
  {
    id: 9,
    leagueName: "HomeBush 9",
    status: "active",
    country: 'us',
    affiliateName: "Thomas Henry",
    totalEvents: 28,
    nextEvent: '12/03/23',
    totalStaff: 4,
    customFees: 'yes',
    isSanctioned: false,
    championshipQualifier: true,
  },
];
